version : '3.7'

services:
   cypress:
      image: "cypress/included:6.8.0"
      depends_on:
         - react-auth-frontend
      environment:
         - CYPRESS_baseUrl=http://react-auth-frontend/
      working_dir: /e2e
      volumes:
         - ./e2e:/e2e/
   react-auth-frontend:
      build:
         context: react-auth-frontend
         dockerfile: Dockerfile
         args:
            REACT_APP_BACKEND_ENDPOINT: http://react-auth-backend:8080/api
      depends_on:
         - react-auth-backend
      ports:
         - 80:80
   react-auth-backend:
      build:
         context: react-auth-backend
         dockerfile: Dockerfile
      healthcheck:
         test: curl --fail -s http://localhost:8080/ || exit 1
         timeout: 45s
         interval: 10s
         retries: 10
      ports:
         - 8080:8080
   