name: React-Auth-Backend CI

on:
  push:
    paths:
     - react-auth-backend/**

defaults:
  run:
    working-directory: ./react-auth-backend/
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
